TOP_MODULE = cse_x25_nonsynth_axilite_mem
SYNTH_SOURCES += $(TOP_MODULE).sv
NONSYNTH_SOURCES += ../../provided_modules/nonsynth_clock_gen.sv
NONSYNTH_SOURCES += ../../provided_modules/nonsynth_reset_gen.sv
-include ../../simulation.mk
-include ../../sby.mk
